// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyEkeTObgIG60l4Hoc1aFTce1mrGQGXPs',
    appId: '1:382305010081:web:7709c7002a97f10b3a0be0',
    messagingSenderId: '382305010081',
    projectId: 'database-ce78d',
    authDomain: 'database-ce78d.firebaseapp.com',
    databaseURL: 'https://database-ce78d-default-rtdb.firebaseio.com',
    storageBucket: 'database-ce78d.appspot.com',
    measurementId: 'G-BF9SSNMKF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtJz_YKgqulcHvcJMbF0nXz5XERWV_zII',
    appId: '1:382305010081:android:c9cc3ffd9b8202073a0be0',
    messagingSenderId: '382305010081',
    projectId: 'database-ce78d',
    databaseURL: 'https://database-ce78d-default-rtdb.firebaseio.com',
    storageBucket: 'database-ce78d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANSdiRaSUhiUlDq1HMsNnY_A1mJFngUrQ',
    appId: '1:382305010081:ios:622470141882c7cf3a0be0',
    messagingSenderId: '382305010081',
    projectId: 'database-ce78d',
    databaseURL: 'https://database-ce78d-default-rtdb.firebaseio.com',
    storageBucket: 'database-ce78d.appspot.com',
    androidClientId: '382305010081-igifv735mk8s8nf16ivr2b08rig3df1j.apps.googleusercontent.com',
    iosClientId: '382305010081-94mhdslt0pl283leggn3cug5e1fnjn1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.furnitureStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANSdiRaSUhiUlDq1HMsNnY_A1mJFngUrQ',
    appId: '1:382305010081:ios:622470141882c7cf3a0be0',
    messagingSenderId: '382305010081',
    projectId: 'database-ce78d',
    databaseURL: 'https://database-ce78d-default-rtdb.firebaseio.com',
    storageBucket: 'database-ce78d.appspot.com',
    androidClientId: '382305010081-igifv735mk8s8nf16ivr2b08rig3df1j.apps.googleusercontent.com',
    iosClientId: '382305010081-94mhdslt0pl283leggn3cug5e1fnjn1k.apps.googleusercontent.com',
    iosBundleId: 'com.example.furnitureStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9tKhwIjEP82uvACSrRQGiE1-3haJxJZw',
    appId: '1:382305010081:web:d9f685892326cad63a0be0',
    messagingSenderId: '382305010081',
    projectId: 'database-ce78d',
    authDomain: 'database-ce78d.firebaseapp.com',
    databaseURL: 'https://database-ce78d-default-rtdb.firebaseio.com',
    storageBucket: 'database-ce78d.appspot.com',
    measurementId: 'G-VF8LX5Q29V',
  );
}
